var listTerritori = [{nome: "Argentina", vicini: ["Peru", "Brasile"], postoPerArmate: [1,1]},
					{nome: "Peru", vicini: ["Argentina", "Brasile", "Venezuela"], postoPerArmate: [2,2]},
					{nome: "Brasile", vicini: ["Peru", "Argentina", "Venezuela", "Africa_del_Nord"], postoPerArmate: [3,3]},
					{nome: "Venezuela", vicini: ["Peru", "Brasile", "America_Centrale"], postoPerArmate: [4,4]},
					{nome: "America_Centrale", vicini: ["Venezuela", "Stati_Uniti_Occidentali", "Stati_Uniti_Orientali"], postoPerArmate: [5,5]},
					{nome: "Stati_Uniti_Occidentali", vicini: ["America_Centrale", "Stati_Uniti_Orientali", "Alberta", "Ontario"], postoPerArmate: [6,6]},
					{nome: "Stati_Uniti_Orientali", vicini: ["America_Centrale", "Stati_Uniti_Occidentali", "Ontario", "Quebec"], postoPerArmate: [7,7]},
					{nome: "Alberta", vicini: ["Stati_Uniti_Occidentali", "Ontario", "Territori_del_Nord_Ovest", "Alaska"], postoPerArmate: [8,8]},
					{nome: "Ontario", vicini: ["Stati_Uniti_Orientali", "Stati_Uniti_Occidentali", "Alberta", "Territori_del_Nord Ovest", "Quebec", "Groenlandia"], postoPerArmate: [9,9]},
					{nome: "Quebec", vicini: ["Stati_Uniti_Orientali", "Groenlandia", "Ontario"], postoPerArmate: [45,67]},
					{nome: "Territori_del_Nord_Ovest", vicini: ["Alaska", "Alberta", "Ontario", "Groenlandia"], postoPerArmate: [10,10]},
					{nome: "Alaska", vicini: ["Alberta", "Territori_del_Nord_Ovest", "Kamchatka"], postoPerArmate: [11,11]},
					{nome: "Groenlandia", vicini: ["Territori_del_Nord_Ovest", "Ontario", "Quebec", "Islanda"], postoPerArmate: [12,12]},
					{nome: "Islanda", vicini: ["Groenlandia", "Gran_Bretagna", "Scandinavia"], postoPerArmate: [13,13]},
					{nome: "Gran_Bretagna", vicini: ["Islanda", "Europa_Occidentale", "Europa_Settentrionale", "Scandinavia"], postoPerArmate: [14,14]},
					{nome: "Scandinavia", vicini: ["Islanda", "Gran_Bretagna", "Europa_Settentrionale", "Ucraina"], postoPerArmate: [15,15]},
					{nome: "Europa_Occidentale", vicini: ["Gran_Bretagna", "Europa_Meridionale", "Africa_del_Nord", "Europa_Settentrionale"], postoPerArmate: [16,16]},
					{nome: "Africa_del_Nord", vicini: ["Brasile", "Congo", "Egitto", "Europa_Occidentale", "Europa_Meridionale"], postoPerArmate: [17,17]},
					{nome: "Congo", vicini: ["Africa_del_Nord", "Africa_del_Sud", "Africa_Orientale"], postoPerArmate: [18,18]},
					{nome: "Africa_del_Sud", vicini: ["Congo", "Madagascar", "Africa_Orientale"], postoPerArmate: [19,19]},
					{nome: "Madagascar", vicini: ["Africa_del_Sud", "Africa_Orientale"], postoPerArmate: [20,20]},
					{nome: "Africa_Orientale", vicini: ["Africa_del_Sud", "Congo", "Africa_del_Nord", "Egitto"], postoPerArmate: [21,21]},
					{nome: "Egitto", vicini: ["Africa_Orientale", "Africa_del_Nord", "Medio_Oriente", "Europa_Meridionale"], postoPerArmate: [22,22]},
					{nome: "Europa_Meridionale", vicini: ["Europa_Occidentale", "Africa_del_Nord", "Egitto", "Medio_Oriente", "Ucraina", "Europa_Settentrionale"], postoPerArmate: [23,23]},
					{nome: "Europa_Settentrionale", vicini: ["Europa_Occidentale", "Gran_Bretagna", "Scandinavia", "Ucraina", "Europa_Meridionale"], postoPerArmate: [23,23]},
					{nome: "Ucraina", vicini: ["Scandinavia", "Europa_Settentrionale", "Europa_Meridionale", "Medio_Oriente", "Afganistan", "Urali"], postoPerArmate: [24,24]},
					{nome: "Urali", vicini: ["Ucraina", "Afganistan", "Siberia", "Cina"], postoPerArmate: [25,25]},
					{nome: "Afghanistan", vicini: ["Ucraina", "Urali", "Cina", "Medio_Oriente"], postoPerArmate: [26,26]},
					{nome: "Medio_Oriente", vicini: ["Egitto", "Europa_Meridionale", "Ucraina", "Afganistan", "Cina", "India"], postoPerArmate: [27,27]},
					{nome: "Siberia", vicini: ["Jacuzia", "Cita", "Urali", "Cina", "Mongolia"], postoPerArmate: [28,28]},
					{nome: "Jacuzia", vicini: ["Siberia", "Kamchatka", "Cita"], postoPerArmate: [29,29]},
					{nome: "Cita", vicini: ["Siberia", "Jacuzia", "Kamchatka", "Mongolia"], postoPerArmate: [30,30]},
					{nome: "Mongolia", vicini: ["Siberia", "Cita", "Kamchatka", "Giappone", "Cina"], postoPerArmate: [31,31]},
					{nome: "Kamchatka", vicini: ["Alaska", "Jacuzia", "Cita", "Mongolia", "Giappone"], postoPerArmate: [32,32]},
					{nome: "Giappone", vicini: ["Kamchatka", "Mongolia"], postoPerArmate: [33,33]},
					{nome: "Cina", vicini: ["Afganistan", "Urali", "Siberia", "Mongolia", "Siam", "India", "Medio_Oriente"], postoPerArmate: [34,34]},
					{nome: "India", vicini: ["Medio_Oriente", "Cina", "Siam"], postoPerArmate: [35,35]},
					{nome: "Siam", vicini: ["India", "Cina", "Indonesia"], postoPerArmate: [36,36]},
					{nome: "Indonesia", vicini: ["Siam", "Nuova_Guinea", "Australia_Occidentale"], postoPerArmate: [37,37]},
					{nome: "Nuova_Guinea", vicini: ["Indonesia", "Australia_Occidentale", "Australia_Orientale"], postoPerArmate: [38,38]},
					{nome: "Australia_Occidentale", vicini: ["Indonesia", "Nuova_Guinea", "Australia_Orientale"], postoPerArmate: [39,39]},
					{nome: "Australia_Orientale", vicini: ["Australia_Occidentale", "Nuova_Guinea"], postoPerArmate: [40,40]}];

